# Site settings
title: Carmelo Mammana
email: carmelomammana8@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  THis is my personal website when you can see all about my projects
baseurl: "/Read-Only-Jekyll-Theme" # the subpath of your site, e.g. /blog/
url: "http://melo96.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  Melo96

# Build settings
markdown: kramdown
